docker_build("todo-app", ".")
k8s_yaml('./k8s/app/deployment.yaml')
k8s_yaml('./k8s/db/deployment.yaml')
k8s_yaml('./k8s/db/service.yaml')

k8s_resource('todo-app', port_forwards=3000)
k8s_resource('todo-db', port_forwards=5432)